const images = {
  p1: require("./bearpages/bear-pg1.png"),
  p2: require("./bearpages/bear-pg2.png"),
  p3: require("./bearpages/bear-pg3.png"),
  p4: require("./bearpages/bear-pg4.png"),
  p5: require("./bearpages/bear-pg5.png"),
  p6: require("./bearpages/bear-pg6.png"),
  p7: require("./bearpages/bear-pg7.png"),
  p8: require("./bearpages/bear-pg8.png"),
  p9: require("./bearpages/bear-pg9.png"),
  p10: require("./bearpages/bear-pg10.png"),
  p11: require("./bearpages/bear-pg11.png"),
  p12: require("./bearpages/bear-pg12.png"),
  p13: require("./bearpages/bear-pg13.png"),
  p14: require("./bearpages/bear-pg14.png"),
  p15: require("./bearpages/bear-pg15.png"),
  p16: require("./bearpages/bear-pg16.png"),
  p17: require("./bearpages/bear-pg17.png"),
  p18: require("./bearpages/bear-pg18.png"),
  p19: require("./bearpages/bear-pg19.png"),
  p20: require("./bearpages/bear-pg20.png"),
  p21: require("./bearpages/bear-pg21.png"),
  p22: require("./bearpages/bear-pg22.png"),
  p23: require("./bearpages/bear-pg23.png"),
  p24: require("./bearpages/bear-pg24.png"),
  p25: require("./bearpages/bear-pg25.png"),
  p26: require("./bearpages/bear-pg26.png"),
  p27: require("./bearpages/bear-pg27.png"),
  p28: require("./bearpages/bear-pg28.png"),
  p29: require("./bearpages/bear-pg29.png"),
  p30: require("./bearpages/bear-pg30.png")  
}
export default images;

